[package]
name = "holochain_nonce"
version.workspace = true
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]
edition = "2021"
description = "This crate is for generating nonces."
license = "Apache-2.0"
repository.workspace = true
documentation = "https://docs.rs/holochain_nonce"

[dependencies]
getrandom = { version = "0.3", default-features = false, features = ["std"] }
holochain_secure_primitive = { workspace = true }
holochain_timestamp = { workspace = true }
subtle-encoding = "0.5"
ts-rs = { version = "12.0", optional = true, features = ["no-serde-warnings"] }

[lints]
workspace = true

[features]
full = []
ts_rs = ["dep:ts-rs"]
