#
# Static checks
#

[tasks.format-check]
workspace = false
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.format-toml-check]
description = "Check that all TOML files are formatted correctly"
workspace = false
command = "taplo"
args = ["format", "--check"]

[tasks.clippy]
workspace = false
command = "cargo"
args = ["clippy", "--workspace", "--all-targets", "--", "--deny=warnings"]

[tasks.doc-check]
description = "Check documentation builds without warnings"
workspace = false
command = "cargo"
args = ["doc", "--workspace", "--no-deps"]
env = { RUSTDOCFLAGS = "--deny=warnings" }

[tasks.wasm-check]
description = "Check that the guest-facing crate builds for the WASM target"
workspace = false
command = "cargo"
args = ["build", "-p", "hdk", "--target", "wasm32-unknown-unknown"]

#
# Tests
#

[tasks.test]
workspace = false
command = "cargo"
args = ["test", "--workspace", "--all-features"]

#
# Tasks that modify content and are not run on CI
#

[tasks.format]
workspace = false
command = "cargo"
args = ["fmt"]

[tasks.format-toml]
workspace = false
command = "taplo"
args = ["format"]

#
# Helper tasks
#

[tasks.static-fmt]
description = "Formatting checks only, with no compilation"
workspace = false
dependencies = ["format-toml-check", "format-check"]

[tasks.static]
description = "Run all static checks"
workspace = false
dependencies = ["static-fmt", "clippy", "doc-check", "wasm-check"]

[tasks.verify]
description = "Run all static checks and tests"
workspace = false
dependencies = ["static", "test"]

[tasks.fix]
description = "Format code and TOML files"
workspace = false
dependencies = ["format", "format-toml"]

[tasks.default]
alias = "verify"

[config]
min_version = "0.37.23"
skip_core_tasks = true
skip_git_env_info = true
skip_rust_env_info = true
